name: Documentation
description: Provide supporting details for a feature or bug in our documentation
labels: kind/documentation
body:
  - type: textarea
    id: documentation
    attributes:
      label: What would you like to see added/updated/deleted in our docs?
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
    validations:
      required: true
