name: ovn-ci

on:
  pull_request:
    branches: [ master ]

env:
  GO_VERSION: "1.19.6"

jobs:
  unit-test:
    name: Run kubevirt unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go

    - name: Run Kubevirt test suite x times
      run: |
        pushd go-controller/pkg/ovn
          count=20
          for i in $(seq $count); do
            go test --ginkgo.v --ginkgo.noColor --ginkgo.focus ".*Kubevirt.*"
          done
        popd

  # separate job for parallelism
  e2e-test:
    name: Run kubevirt e2e tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go
    - name: Start kind
      env:
        KIND_IPV6_SUPPORT: true
        KIND_IPV4_SUPPORT: true
        KIND_INSTALL_KUBEVIRT: true
        OVN_ENABLE_INTERCONNECT: true
        GO_VERSION: "1.19.6"
        KIND_ALLOW_SYSTEM_WRITES: true
      run: |
        make -C test install-kind
    - name: Run kubevirt e2e tests
      run: |
        pushd test/e2e
          export KUBECONFIG=~/ovn.conf
          count=10
          for i in $(seq $count); do
            go test --ginkgo.v --ginkgo.noColor --ginkgo.focus ".*Kubevirt.*pre-copy.*"
          done
        popd
